version: "3"
services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"

  profile-api:
    depends_on:
      - mysql
    build: .
    ports:
      - "8080:80"

  auth-api:
    depends_on:
      - mysql
    build: /home/ubuntu/PinArt-Authentication-MS
    ports:
      - "4000:80"
